var tshitsList = [
    {
        id: "ts0",
        name: "EGATOR LION",
        price: 320.000,
        img: "./img/tshirts/1.1.jpg",
        img2: "./img/tshirts/1.2.jpg",
        img3: "./img/tshirts/1.3.jpg",
        img4: "./img/tshirts/1.4.jpg",
    },
    {
        id: "ts1",
        name: "EGATOR CROCO",
        price: 330.000,
        img: "./img/tshirts/2.1.jpg",
        img2: "./img/tshirts/2.2.jpg",
        img3: "./img/tshirts/2.3.jpg",
        img4: "./img/tshirts/2.4.jpg",
    },
    {
        id: "ts2",
        name: "EGATOR POPULAR",
        price: 310.000,
        img: "./img/tshirts/3.1.jpg",
        img2: "./img/tshirts/3.2.jpg",
        img3: "./img/tshirts/3.3.jpg",
        img4: "./img/tshirts/3.4.jpg",
    },
    {
        id: "ts3",
        name: "EGATOR DINOSAUR",
        price: 350.000,
        img: "./img/tshirts/4.1.jpg",
        img2: "./img/tshirts/4.2.jpg",
        img3: "./img/tshirts/4.3.jpg",
        img4: "./img/tshirts/4.4.jpg",
    },
    {
        id: "ts4",
        name: "EGATOR LOGO 2.0",
        price: 320.000,
        img: "./img/tshirts/5.1.jpg",
        img2: "./img/tshirts/5.2.jpg",
        img3: "./img/tshirts/5.3.jpg",
        img4: "./img/tshirts/5.4.jpg",
    },
    {
        id: "ts5",
        name: "EGATOR FLORAL",
        price: 300.000,
        img: "./img/tshirts/6.1.jpg",
        img2: "./img/tshirts/6.2.jpg",
        img3: "./img/tshirts/6.3.jpg",
        img4: "./img/tshirts/6.4.jpg",
    },
    {
        id: "ts6",
        name: "EGATOR BTC",
        price: 400.000,
        img: "./img/tshirts/7.1.jpg",
        img2: "./img/tshirts/7.2.jpg",
        img3: "./img/tshirts/7.3.jpg",
        img4: "./img/tshirts/7.4.jpg",
    },
    {
        id: "ts7",
        name: "EGATOR SHARK",
        price: 300.000,
        img: "./img/tshirts/8.1.jpg",
        img2: "./img/tshirts/8.2.jpg",
        img3: "./img/tshirts/8.3.jpg",
        img4: "./img/tshirts/8.4.jpg",
    },
    {
        id: "ts8",
        name: "EGATOR MILI",
        price: 320.000,
        img: "./img/tshirts/9.1.jpg",
        img2: "./img/tshirts/9.2.jpg",
        img3: "./img/tshirts/9.3.jpg",
        img4: "./img/tshirts/9.4.jpg",
    },
    {
        id: "ts9",
        name: "EGATOR COCA",
        price: 335.000,
        img: "./img/tshirts/10.1.jpg",
        img2: "./img/tshirts/10.2.jpg",
        img3: "./img/tshirts/10.3.jpg",
        img4: "./img/tshirts/10.4.jpg",
    },
    {
        id: "ts10",
        name: "EGATOR FRIEND",
        price: 370.000,
        img: "./img/tshirts/11.1.jpg",
        img2: "./img/tshirts/11.2.jpg",
        img3: "./img/tshirts/11.3.jpg",
        img4: "./img/tshirts/11.4.jpg",
    },
    {
        id: "ts11",
        name: "EGATOR GOD",
        price: 315.000,
        img: "./img/tshirts/12.1.jpg",
        img2: "./img/tshirts/12.2.jpg",
        img3: "./img/tshirts/12.3.jpg",
        img4: "./img/tshirts/12.4.jpg",
    },
    {
        id: "ts12",
        name: "EGATOR LOGO 3.0",
        price: 390.000,
        img: "./img/tshirts/13.1.jpg",
        img2: "./img/tshirts/13.2.jpg",
        img3: "./img/tshirts/13.3.jpg",
        img4: "./img/tshirts/13.4.jpg",
    },
    {
        id: "ts13",
        name: "EGATOR LOCAL",
        price: 450.000,
        img: "./img/tshirts/14.1.jpg",
        img2: "./img/tshirts/14.2.jpg",
        img3: "./img/tshirts/14.3.jpg",
        img4: "./img/tshirts/14.4.jpg",
    },
    {
        id: "ts14",
        name: "EGATOR PLUS",
        price: 345.000,
        img: "./img/tshirts/15.1.jpg",
        img2: "./img/tshirts/15.2.jpg",
        img3: "./img/tshirts/15.3.jpg",
        img4: "./img/tshirts/15.4.jpg",

    },
    {
        id: "ts15",
        name: "EGATOR DOLPHIN",
        price: 360.000,
        img: "./img/tshirts/16.1.jpg",
        img2: "./img/tshirts/16.2.jpg",
        img3: "./img/tshirts/16.3.jpg",
        img4: "./img/tshirts/16.4.jpg",
    },
]


var hoodiesList = [
    {
        id: "hd0",
        name: "EGATOR DORAE",
        price: 680.000,
        img: "./img/hoodies/1.1.jpg",
        img2: "./img/hoodies/1.2.jpg",
        img3: "./img/hoodies/1.3.jpg",
        img4: "./img/hoodies/1.4.jpg",
    },
    {
        id: "hd1",
        name: "EGATOR ZIPPER",
        price: 750.000,
        img: "./img/hoodies/2.1.jpg",
        img2: "./img/hoodies/2.2.jpg",
        img3: "./img/hoodies/2.3.jpg",
        img4: "./img/hoodies/2.4.jpg",
    },
    {
        id: "hd2",
        name: "EGATOR CREAM",
        price: 420.000,
        img: "./img/hoodies/3.1.jpg",
        img2: "./img/hoodies/3.2.jpg",
        img3: "./img/hoodies/3.3.jpg",
        img4: "./img/hoodies/3.4.jpg",
    },
    {
        id: "hd3",
        name: "EGATOR COLLAB",
        price: 530.000,
        img: "./img/hoodies/4.1.jpg",
        img2: "./img/hoodies/4.2.jpg",
        img3: "./img/hoodies/4.3.jpg",
        img4: "./img/hoodies/4.4.jpg",
    },
    {
        id: "hd4",
        name: "EGATOR MINI",
        price: 620.000,
        img: "./img/hoodies/5.1.jpg",
        img2: "./img/hoodies/5.2.jpg",
        img3: "./img/hoodies/5.3.jpg",
        img4: "./img/hoodies/5.4.jpg",
    },
    {
        id: "hd5",
        name: "EGATOR MAX",
        price: 800.000,
        img: "./img/hoodies/6.1.jpg",
        img2: "./img/hoodies/6.2.jpg",
        img3: "./img/hoodies/6.3.jpg",
        img4: "./img/hoodies/6.4.jpg",
    },
    {
        id: "hd6",
        name: "EGATOR TRAVEL",
        price: 750.000,
        img: "./img/hoodies/7.1.jpg",
        img2: "./img/hoodies/7.2.jpg",
        img3: "./img/hoodies/7.3.jpg",
        img4: "./img/hoodies/7.4.jpg",
    },
    {
        id: "hd7",
        name: "EGATOR TIGER",
        price: 720.000,
        img: "./img/hoodies/8.1.jpg",
        img2: "./img/hoodies/8.2.jpg",
        img3: "./img/hoodies/8.3.jpg",
        img4: "./img/hoodies/8.4.jpg",
    },
]

var sweatersList = [
    {
        id: "st0",
        name: "EGATOR BLACK",
        price: 200.000,
        img: "./img/sweater/1.1.jpg",
        img2: "./img/sweater/1.2.jpg",
        img3: "./img/sweater/1.3.jpg",
        img4: "./img/sweater/1.4.jpg",
    },
    {
        id: "st1",
        name: "EGATOR GREY",
        price: 250.000,
        img: "./img/sweater/2.1.jpg",
        img2: "./img/sweater/2.2.jpg",
        img3: "./img/sweater/2.3.jpg",
        img4: "./img/sweater/2.4.jpg",
    },
    {
        id: "st2",
        name: "EGATOR OLIVE",
        price: 220.000,
        img: "./img/sweater/3.1.jpg",
        img2: "./img/sweater/3.2.jpg",
        img3: "./img/sweater/3.3.jpg",
        img4: "./img/sweater/3.4.jpg",
    },
    {
        id: "st3",
        name: "EGATOR RED",
        price: 240.000,
        img: "./img/sweater/4.1.jpg",
        img2: "./img/sweater/4.2.jpg",
        img3: "./img/sweater/4.3.jpg",
        img4: "./img/sweater/4.4.jpg",
    },
]

var productsList = [
    {
        id: "ts0",
        name: "EGATOR LION",
        price: 320.000,
        img: "./img/tshirts/1.1.jpg",
        img2: "./img/tshirts/1.2.jpg",
        img3: "./img/tshirts/1.3.jpg",
        img4: "./img/tshirts/1.4.jpg",
    },
    {
        id: "ts1",
        name: "EGATOR CROCO",
        price: 330.000,
        img: "./img/tshirts/2.1.jpg",
        img2: "./img/tshirts/2.2.jpg",
        img3: "./img/tshirts/2.3.jpg",
        img4: "./img/tshirts/2.4.jpg",
    },
    {
        id: "ts2",
        name: "EGATOR POPULAR",
        price: 310.000,
        img: "./img/tshirts/3.1.jpg",
        img2: "./img/tshirts/3.2.jpg",
        img3: "./img/tshirts/3.3.jpg",
        img4: "./img/tshirts/3.4.jpg",
    },
    {
        id: "ts3",
        name: "EGATOR DINOSAUR",
        price: 350.000,
        img: "./img/tshirts/4.1.jpg",
        img2: "./img/tshirts/4.2.jpg",
        img3: "./img/tshirts/4.3.jpg",
        img4: "./img/tshirts/4.4.jpg",
    },
    {
        id: "ts4",
        name: "EGATOR LOGO 2.0",
        price: 320.000,
        img: "./img/tshirts/5.1.jpg",
        img2: "./img/tshirts/5.2.jpg",
        img3: "./img/tshirts/5.3.jpg",
        img4: "./img/tshirts/5.4.jpg",
    },
    {
        id: "ts5",
        name: "EGATOR FLORAL",
        price: 300.000,
        img: "./img/tshirts/6.1.jpg",
        img2: "./img/tshirts/6.2.jpg",
        img3: "./img/tshirts/6.3.jpg",
        img4: "./img/tshirts/6.4.jpg",
    },
    {
        id: "ts6",
        name: "EGATOR BTC",
        price: 400.000,
        img: "./img/tshirts/7.1.jpg",
        img2: "./img/tshirts/7.2.jpg",
        img3: "./img/tshirts/7.3.jpg",
        img4: "./img/tshirts/7.4.jpg",
    },
    {
        id: "ts7",
        name: "EGATOR SHARK",
        price: 300.000,
        img: "./img/tshirts/8.1.jpg",
        img2: "./img/tshirts/8.2.jpg",
        img3: "./img/tshirts/8.3.jpg",
        img4: "./img/tshirts/8.4.jpg",
    },
    {
        id: "ts8",
        name: "EGATOR MILI",
        price: 320.000,
        img: "./img/tshirts/9.1.jpg",
        img2: "./img/tshirts/9.2.jpg",
        img3: "./img/tshirts/9.3.jpg",
        img4: "./img/tshirts/9.4.jpg",
    },
    {
        id: "ts9",
        name: "EGATOR COCA",
        price: 335.000,
        img: "./img/tshirts/10.1.jpg",
        img2: "./img/tshirts/10.2.jpg",
        img3: "./img/tshirts/10.3.jpg",
        img4: "./img/tshirts/10.4.jpg",
    },
    {
        id: "ts10",
        name: "EGATOR FRIEND",
        price: 370.000,
        img: "./img/tshirts/11.1.jpg",
        img2: "./img/tshirts/11.2.jpg",
        img3: "./img/tshirts/11.3.jpg",
        img4: "./img/tshirts/11.4.jpg",
    },
    {
        id: "ts11",
        name: "EGATOR GOD",
        price: 315.000,
        img: "./img/tshirts/12.1.jpg",
        img2: "./img/tshirts/12.2.jpg",
        img3: "./img/tshirts/12.3.jpg",
        img4: "./img/tshirts/12.4.jpg",
    },
    {
        id: "ts12",
        name: "EGATOR LOGO 3.0",
        price: 390.000,
        img: "./img/tshirts/13.1.jpg",
        img2: "./img/tshirts/13.2.jpg",
        img3: "./img/tshirts/13.3.jpg",
        img4: "./img/tshirts/13.4.jpg",
    },
    {
        id: "ts13",
        name: "EGATOR LOCAL",
        price: 450.000,
        img: "./img/tshirts/14.1.jpg",
        img2: "./img/tshirts/14.2.jpg",
        img3: "./img/tshirts/14.3.jpg",
        img4: "./img/tshirts/14.4.jpg",
    },
    {
        id: "ts14",
        name: "EGATOR PLUS",
        price: 345.000,
        img: "./img/tshirts/15.1.jpg",
        img2: "./img/tshirts/15.2.jpg",
        img3: "./img/tshirts/15.3.jpg",
        img4: "./img/tshirts/15.4.jpg",

    },
    {
        id: "ts15",
        name: "EGATOR DOLPHIN",
        price: 360.000,
        img: "./img/tshirts/16.1.jpg",
        img2: "./img/tshirts/16.2.jpg",
        img3: "./img/tshirts/16.3.jpg",
        img4: "./img/tshirts/16.4.jpg",
    },
    {
        id: "hd0",
        name: "EGATOR DORAE",
        price: 680.000,
        img: "./img/hoodies/1.1.jpg",
        img2: "./img/hoodies/1.2.jpg",
        img3: "./img/hoodies/1.3.jpg",
        img4: "./img/hoodies/1.4.jpg",
    },
    {
        id: "hd1",
        name: "EGATOR ZIPPER",
        price: 750.000,
        img: "./img/hoodies/2.1.jpg",
        img2: "./img/hoodies/2.2.jpg",
        img3: "./img/hoodies/2.3.jpg",
        img4: "./img/hoodies/2.4.jpg",
    },
    {
        id: "hd2",
        name: "EGATOR CREAM",
        price: 420.000,
        img: "./img/hoodies/3.1.jpg",
        img2: "./img/hoodies/3.2.jpg",
        img3: "./img/hoodies/3.3.jpg",
        img4: "./img/hoodies/3.4.jpg",
    },
    {
        id: "hd3",
        name: "EGATOR COLLAB",
        price: 530.000,
        img: "./img/hoodies/4.1.jpg",
        img2: "./img/hoodies/4.2.jpg",
        img3: "./img/hoodies/4.3.jpg",
        img4: "./img/hoodies/4.4.jpg",
    },
    {
        id: "hd4",
        name: "EGATOR MINI",
        price: 620.000,
        img: "./img/hoodies/5.1.jpg",
        img2: "./img/hoodies/5.2.jpg",
        img3: "./img/hoodies/5.3.jpg",
        img4: "./img/hoodies/5.4.jpg",
    },
    {
        id: "hd5",
        name: "EGATOR MAX",
        price: 800.000,
        img: "./img/hoodies/6.1.jpg",
        img2: "./img/hoodies/6.2.jpg",
        img3: "./img/hoodies/6.3.jpg",
        img4: "./img/hoodies/6.4.jpg",
    },
    {
        id: "hd6",
        name: "EGATOR TRAVEL",
        price: 750.000,
        img: "./img/hoodies/7.1.jpg",
        img2: "./img/hoodies/7.2.jpg",
        img3: "./img/hoodies/7.3.jpg",
        img4: "./img/hoodies/7.4.jpg",
    },
    {
        id: "hd7",
        name: "EGATOR TIGER",
        price: 720.000,
        img: "./img/hoodies/8.1.jpg",
        img2: "./img/hoodies/8.2.jpg",
        img3: "./img/hoodies/8.3.jpg",
        img4: "./img/hoodies/8.4.jpg",
    },
    {
        id: "st0",
        name: "EGATOR BLACK",
        price: 200.000,
        img: "./img/sweater/1.1.jpg",
        img2: "./img/sweater/1.2.jpg",
        img3: "./img/sweater/1.3.jpg",
        img4: "./img/sweater/1.4.jpg",
    },
    {
        id: "st1",
        name: "EGATOR GREY",
        price: 250.000,
        img: "./img/sweater/2.1.jpg",
        img2: "./img/sweater/2.2.jpg",
        img3: "./img/sweater/2.3.jpg",
        img4: "./img/sweater/2.4.jpg",
    },
    {
        id: "st2",
        name: "EGATOR OLIVE",
        price: 220.000,
        img: "./img/sweater/3.1.jpg",
        img2: "./img/sweater/3.2.jpg",
        img3: "./img/sweater/3.3.jpg",
        img4: "./img/sweater/3.4.jpg",
    },
    {
        id: "st3",
        name: "EGATOR RED",
        price: 240.000,
        img: "./img/sweater/4.1.jpg",
        img2: "./img/sweater/4.2.jpg",
        img3: "./img/sweater/4.3.jpg",
        img4: "./img/sweater/4.4.jpg",
    },
]

if (localStorage.getItem('productsList') === null) {
    console.log("Push data!");
    localStorage.setItem('productsList', JSON.stringify(productsList))
    localStorage.setItem("tshitsList", JSON.stringify(tshitsList))
    localStorage.setItem("hoodiesList", JSON.stringify(hoodiesList))
    localStorage.setItem("sweatersList", JSON.stringify(sweatersList))
}