const tshitsList = [
    {
        id: "ts0",
        name: "LEVENTS® 1 MILLION TEE",
        price: 320.000,
        img: "./img/tshirts/1.1.jpg",
        img2: "./img/tshirts/1.2.jpg",
        img3: "./img/tshirts/1.3.jpg",
        img4: "./img/tshirts/1.4.jpg",
    },
    {
        id: "ts1",
        name: "LEVENTS® CROCODILE TEE",
        price: 330.000,
        img: "./img/tshirts/2.1.jpg",
        img2: "./img/tshirts/2.2.jpg",
        img3: "./img/tshirts/2.3.jpg",
        img4: "./img/tshirts/2.4.jpg",
    },
    {
        id: "ts2",
        name: "LEVENTS® POPULAR TEE",
        price: 310.000,
        img: "./img/tshirts/3.1.jpg",
        img2: "./img/tshirts/3.2.jpg",
        img3: "./img/tshirts/3.3.jpg",
        img4: "./img/tshirts/3.4.jpg",
    },
    {
        id: "ts3",
        name: "LEVENTS® DINOSAUR TEE",
        price: 350.000,
        img: "./img/tshirts/4.1.jpg",
        img2: "./img/tshirts/4.2.jpg",
        img3: "./img/tshirts/4.3.jpg",
        img4: "./img/tshirts/4.4.jpg",
    },
    {
        id: "ts4",
        name: "LEVENTS® LOGO 2.0 TEE",
        price: 320.000,
        img: "./img/tshirts/5.1.jpg",
        img2: "./img/tshirts/5.2.jpg",
        img3: "./img/tshirts/5.3.jpg",
        img4: "./img/tshirts/5.4.jpg",
    },
    {
        id: "ts5",
        name: "LEVENTS® FLORAL TEE",
        price: 300.000,
        img: "./img/tshirts/6.1.jpg",
        img2: "./img/tshirts/6.2.jpg",
        img3: "./img/tshirts/6.3.jpg",
        img4: "./img/tshirts/6.4.jpg",
    },
    {
        id: "ts6",
        name: "LEVENTS® PLUS CLUB TEE",
        price: 400.000,
        img: "./img/tshirts/7.1.jpg",
        img2: "./img/tshirts/7.2.jpg",
        img3: "./img/tshirts/7.3.jpg",
        img4: "./img/tshirts/7.4.jpg",
    },
    {
        id: "ts7",
        name: "LEVENTS® SHARK TEE",
        price: 300.000,
        img: "./img/tshirts/8.1.jpg",
        img2: "./img/tshirts/8.2.jpg",
        img3: "./img/tshirts/8.3.jpg",
        img4: "./img/tshirts/8.4.jpg",
    },
    {
        id: "ts8",
        name: "LEVENTS® 1 MILLION TEE",
        price: 320.000,
        img: "./img/tshirts/9.1.jpg",
        img2: "./img/tshirts/9.2.jpg",
        img3: "./img/tshirts/9.3.jpg",
        img4: "./img/tshirts/9.4.jpg",
    },
    {
        id: "ts9",
        name: "LEVENTS® COCA TEE",
        price: 335.000,
        img: "./img/tshirts/10.1.jpg",
        img2: "./img/tshirts/10.2.jpg",
        img3: "./img/tshirts/10.3.jpg",
        img4: "./img/tshirts/10.4.jpg",
    },
    {
        id: "ts10",
        name: "LEVENTS® FRIENDSHIP TEE",
        price: 370.000,
        img: "./img/tshirts/11.1.jpg",
        img2: "./img/tshirts/11.2.jpg",
        img3: "./img/tshirts/11.3.jpg",
        img4: "./img/tshirts/11.4.jpg",
    },
    {
        id: "ts11",
        name: "LEVENTS® GOD TEE",
        price: 315.000,
        img: "./img/tshirts/12.1.jpg",
        img2: "./img/tshirts/12.2.jpg",
        img3: "./img/tshirts/12.3.jpg",
        img4: "./img/tshirts/12.4.jpg",
    },
    {
        id: "ts12",
        name: "LEVENTS® LOGO 3.0 TEE",
        price: 390.000,
        img: "./img/tshirts/13.1.jpg",
        img2: "./img/tshirts/13.2.jpg",
        img3: "./img/tshirts/13.3.jpg",
        img4: "./img/tshirts/13.4.jpg",
    },
    {
        id: "ts13",
        name: "LEVENTS® LOCAL TEE",
        price: 450.000,
        img: "./img/tshirts/14.1.jpg",
        img2: "./img/tshirts/14.2.jpg",
        img3: "./img/tshirts/14.3.jpg",
        img4: "./img/tshirts/14.4.jpg",
    },
    {
        id: "ts14",
        name: "LEVENTS® PLUS TEE",
        price: 345.000,
        img: "./img/tshirts/15.1.jpg",
        img2: "./img/tshirts/15.2.jpg",
        img3: "./img/tshirts/15.3.jpg",
        img4: "./img/tshirts/15.4.jpg",

    },
    {
        id: "ts15",
        name: "LEVENTS® DOLPHIN TEE",
        price: 360.000,
        img: "./img/tshirts/16.1.jpg",
        img2: "./img/tshirts/16.2.jpg",
        img3: "./img/tshirts/16.3.jpg",
        img4: "./img/tshirts/16.4.jpg",
    },
]


const hoodieList = [
    {
        id: "hd0",
        name: "LEVENTS® DORAEMON",
        price: 680.000,
        img: "./img/hoddie/1.1.jpg",
        img2: "./img/hoddie/1.1.jpg",
        img3: "./img/hoddie/1.1.jpg",
        img4: "./img/hoddie/1.1.jpg",
    },
    {
        id: "hd1",
        name: "LEVENTS® ZIPPER",
        price: 750.000,
        img: "./img/hoddie/2.1.jpg",
        img2: "./img/hoddie/2.1.jpg",
        img3: "./img/hoddie/2.1.jpg",
        img4: "./img/hoddie/2.1.jpg",
    },
    {
        id: "hd2",
        name: "LEVENTS® CREAM",
        price: 420.000,
        img: "./img/hoddie/3.1.jpg",
        img2: "./img/hoddie/3.1.jpg",
        img3: "./img/hoddie/3.1.jpg",
        img4: "./img/hoddie/3.1.jpg",
    },
    {
        id: "hd3",
        name: "LEVENTS® COLLAB",
        price: 530.000,
        img: "./img/hoddie/4.1.jpg",
        img2: "./img/hoddie/4.1.jpg",
        img3: "./img/hoddie/4.1.jpg",
        img4: "./img/hoddie/4.1.jpg",
    },
    {
        id: "hd4",
        name: "LEVENTS® MINI",
        price: 620.000,
        img: "./img/hoddie/5.1.jpg",
        img2: "./img/hoddie/5.1.jpg",
        img3: "./img/hoddie/5.1.jpg",
        img4: "./img/hoddie/5.1.jpg",
    },
    {
        id: "hd5",
        name: "LEVENTS® MAX",
        price: 800.000,
        img: "./img/hoddie/6.1.jpg",
        img2: "./img/hoddie/6.1.jpg",
        img3: "./img/hoddie/6.1.jpg",
        img4: "./img/hoddie/6.1.jpg",
    },
    {
        id: "hd6",
        name: "LEVENTS® TRAVEL",
        price: 750.000,
        img: "./img/hoddie/7.1.jpg",
        img2: "./img/hoddie/7.1.jpg",
        img3: "./img/hoddie/7.1.jpg",
        img4: "./img/hoddie/7.1.jpg",
    },
    {
        id: "hd7",
        name: "LEVENTS® TIGER",
        price: 720.000,
        img: "./img/hoddie/8.1.jpg",
        img2: "./img/hoddie/8.1.jpg",
        img3: "./img/hoddie/8.1.jpg",
        img4: "./img/hoddie/8.1.jpg",
    }
]

const sweaterList = [
    {
        id: "st0",
        name: "LEVENTS® BLACK",
        price: 200.000,
        img: "./img/sweater/1.1.jpg",
        img2: "./img/sweater/1.1.jpg",
        img3: "./img/sweater/1.1.jpg",
        img4: "./img/sweater/1.1.jpg",
    },
    {
        id: "st1",
        name: "LEVENTS® GREY",
        price: 250.000,
        img: "./img/sweater/2.1.jpg",
        img2: "./img/sweater/2.1.jpg",
        img3: "./img/sweater/2.1.jpg",
        img4: "./img/sweater/2.1.jpg",
    },
    {
        id: "st2",
        name: "LEVENTS® OLIVE",
        price: 220.000,
        img: "./img/sweater/3.1.jpg",
        img2: "./img/sweater/3.1.jpg",
        img3: "./img/sweater/3.1.jpg",
        img4: "./img/sweater/3.1.jpg",
    },
    {
        id: "st3",
        name: "LEVENTS® RED",
        price: 240.000,
        img: "./img/sweater/4.1.jpg",
        img2: "./img/sweater/4.1.jpg",
        img3: "./img/sweater/4.1.jpg",
        img4: "./img/sweater/4.1.jpg",
    },
]

export  {tshitsList,hoodieList, sweaterList}
