var productsList = [
    {
        id: "ts",
        name: "LION",
        price: 320.000,
        img: "./img/tshirts/1.1.jpg",
        img2: "./img/tshirts/1.2.jpg",
        img3: "./img/tshirts/1.3.jpg",
        img4: "./img/tshirts/1.4.jpg",
    },
    {
        id: "ts",
        name: "CROCO",
        price: 330.000,
        img: "./img/tshirts/2.1.jpg",
        img2: "./img/tshirts/2.2.jpg",
        img3: "./img/tshirts/2.3.jpg",
        img4: "./img/tshirts/2.4.jpg",
    },
    {
        id: "ts",
        name: "POPULAR",
        price: 310.000,
        img: "./img/tshirts/3.1.jpg",
        img2: "./img/tshirts/3.2.jpg",
        img3: "./img/tshirts/3.3.jpg",
        img4: "./img/tshirts/3.4.jpg",
    },
    {
        id: "ts",
        name: "DINOSAUR",
        price: 350.000,
        img: "./img/tshirts/4.1.jpg",
        img2: "./img/tshirts/4.2.jpg",
        img3: "./img/tshirts/4.3.jpg",
        img4: "./img/tshirts/4.4.jpg",
    },
    {
        id: "ts",
        name: "LOGO 2.0",
        price: 320.000,
        img: "./img/tshirts/5.1.jpg",
        img2: "./img/tshirts/5.2.jpg",
        img3: "./img/tshirts/5.3.jpg",
        img4: "./img/tshirts/5.4.jpg",
    },
    {
        id: "ts",
        name: "FLORAL",
        price: 300.000,
        img: "./img/tshirts/6.1.jpg",
        img2: "./img/tshirts/6.2.jpg",
        img3: "./img/tshirts/6.3.jpg",
        img4: "./img/tshirts/6.4.jpg",
    },
    {
        id: "ts",
        name: "BTC",
        price: 400.000,
        img: "./img/tshirts/7.1.jpg",
        img2: "./img/tshirts/7.2.jpg",
        img3: "./img/tshirts/7.3.jpg",
        img4: "./img/tshirts/7.4.jpg",
    },
    {
        id: "ts",
        name: "SHARK",
        price: 300.000,
        img: "./img/tshirts/8.1.jpg",
        img2: "./img/tshirts/8.2.jpg",
        img3: "./img/tshirts/8.3.jpg",
        img4: "./img/tshirts/8.4.jpg",
    },
    {
        id: "ts",
        name: "MILI",
        price: 320.000,
        img: "./img/tshirts/9.1.jpg",
        img2: "./img/tshirts/9.2.jpg",
        img3: "./img/tshirts/9.3.jpg",
        img4: "./img/tshirts/9.4.jpg",
    },
    {
        id: "ts",
        name: "COCA",
        price: 335.000,
        img: "./img/tshirts/10.1.jpg",
        img2: "./img/tshirts/10.2.jpg",
        img3: "./img/tshirts/10.3.jpg",
        img4: "./img/tshirts/10.4.jpg",
    },
    {
        id: "ts",
        name: "FRIEND",
        price: 370.000,
        img: "./img/tshirts/11.1.jpg",
        img2: "./img/tshirts/11.2.jpg",
        img3: "./img/tshirts/11.3.jpg",
        img4: "./img/tshirts/11.4.jpg",
    },
    {
        id: "ts",
        name: "GOD",
        price: 315.000,
        img: "./img/tshirts/12.1.jpg",
        img2: "./img/tshirts/12.2.jpg",
        img3: "./img/tshirts/12.3.jpg",
        img4: "./img/tshirts/12.4.jpg",
    },
    {
        id: "ts",
        name: "LOGO 3.0",
        price: 390.000,
        img: "./img/tshirts/13.1.jpg",
        img2: "./img/tshirts/13.2.jpg",
        img3: "./img/tshirts/13.3.jpg",
        img4: "./img/tshirts/13.4.jpg",
    },
    {
        id: "ts",
        name: "LOCAL",
        price: 450.000,
        img: "./img/tshirts/14.1.jpg",
        img2: "./img/tshirts/14.2.jpg",
        img3: "./img/tshirts/14.3.jpg",
        img4: "./img/tshirts/14.4.jpg",
    },
    {
        id: "ts",
        name: "PLUS",
        price: 345.000,
        img: "./img/tshirts/15.1.jpg",
        img2: "./img/tshirts/15.2.jpg",
        img3: "./img/tshirts/15.3.jpg",
        img4: "./img/tshirts/15.4.jpg",

    },
    {
        id: "ts",
        name: "DOLPHIN",
        price: 360.000,
        img: "./img/tshirts/16.1.jpg",
        img2: "./img/tshirts/16.2.jpg",
        img3: "./img/tshirts/16.3.jpg",
        img4: "./img/tshirts/16.4.jpg",
    },
    {
        id: "hd",
        name: "DORAE",
        price: 680.000,
        img: "./img/hoodies/1.1.jpg",
        img2: "./img/hoodies/1.2.jpg",
        img3: "./img/hoodies/1.3.jpg",
        img4: "./img/hoodies/1.4.jpg",
    },
    {
        id: "hd",
        name: "ZIPPER",
        price: 750.000,
        img: "./img/hoodies/2.1.jpg",
        img2: "./img/hoodies/2.2.jpg",
        img3: "./img/hoodies/2.3.jpg",
        img4: "./img/hoodies/2.4.jpg",
    },
    {
        id: "hd",
        name: "CREAM",
        price: 420.000,
        img: "./img/hoodies/3.1.jpg",
        img2: "./img/hoodies/3.2.jpg",
        img3: "./img/hoodies/3.3.jpg",
        img4: "./img/hoodies/3.4.jpg",
    },
    {
        id: "hd",
        name: "COLLAB",
        price: 530.000,
        img: "./img/hoodies/4.1.jpg",
        img2: "./img/hoodies/4.2.jpg",
        img3: "./img/hoodies/4.3.jpg",
        img4: "./img/hoodies/4.4.jpg",
    },
    {
        id: "hd",
        name: "MINI",
        price: 620.000,
        img: "./img/hoodies/5.1.jpg",
        img2: "./img/hoodies/5.2.jpg",
        img3: "./img/hoodies/5.3.jpg",
        img4: "./img/hoodies/5.4.jpg",
    },
    {
        id: "hd",
        name: "MAX",
        price: 800.000,
        img: "./img/hoodies/6.1.jpg",
        img2: "./img/hoodies/6.2.jpg",
        img3: "./img/hoodies/6.3.jpg",
        img4: "./img/hoodies/6.4.jpg",
    },
    {
        id: "hd",
        name: "TRAVEL",
        price: 750.000,
        img: "./img/hoodies/7.1.jpg",
        img2: "./img/hoodies/7.2.jpg",
        img3: "./img/hoodies/7.3.jpg",
        img4: "./img/hoodies/7.4.jpg",
    },
    {
        id: "hd",
        name: "TIGER",
        price: 720.000,
        img: "./img/hoodies/8.1.jpg",
        img2: "./img/hoodies/8.2.jpg",
        img3: "./img/hoodies/8.3.jpg",
        img4: "./img/hoodies/8.4.jpg",
    },
    {
        id: "st",
        name: "BLACK",
        price: 200.000,
        img: "./img/sweater/1.1.jpg",
        img2: "./img/sweater/1.2.jpg",
        img3: "./img/sweater/1.3.jpg",
        img4: "./img/sweater/1.4.jpg",
    },
    {
        id: "st",
        name: "GREY",
        price: 250.000,
        img: "./img/sweater/2.1.jpg",
        img2: "./img/sweater/2.2.jpg",
        img3: "./img/sweater/2.3.jpg",
        img4: "./img/sweater/2.4.jpg",
    },
    {
        id: "st",
        name: "OLIVE",
        price: 220.000,
        img: "./img/sweater/3.1.jpg",
        img2: "./img/sweater/3.2.jpg",
        img3: "./img/sweater/3.3.jpg",
        img4: "./img/sweater/3.4.jpg",
    },
    {
        id: "st",
        name: "RED",
        price: 240.000,
        img: "./img/sweater/4.1.jpg",
        img2: "./img/sweater/4.2.jpg",
        img3: "./img/sweater/4.3.jpg",
        img4: "./img/sweater/4.4.jpg",
    },
]

if (localStorage.getItem('productsList') === null) {
    localStorage.setItem('productsList', JSON.stringify(productsList))
}